#!/bin/bash
# Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
# Start Nginx service
sudo service nginx start
# Create a custom HTTP response header
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    location / {
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        try_files $uri $uri/ =404;
    }
}' | sudo tee /etc/nginx/sites-available/default
# Restart Nginx service
sudo service nginx restart
