#!/usr/bin/env bash
# This script installs and configures HAProxy on the lb-01 server

# Update package index
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Edit HAProxy configuration file
sudo cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 432111-web-01:80 check
    server web-02 432111-web-02:80 check
EOF

# Restart HAProxy service
sudo service haproxy restart

# Verify HAProxy status
sudo service haproxy status

# Output success message
echo "HAProxy installed and configured successfully."

