#!/usr/bin/env bash
#using while and if loop to print "Best School" and "hi"
i=0
while [ "$i" -lt 10 ]; do
	if [ "$i" -eq 9 ]; then
		echo "Hi"
		echo "Best School"
	else
		echo "Best School"
	fi
	((i++))
done
