#!/usr/bin/env bash
#using while and case statement
i=1
while [ "$i" -lt 21 ]; do
	case "$i" in
		4)
			echo "$i"
			echo "bad luck from china"
			;;
		9)
			echo "$i"
			echo "bad luck from japan"
			;;
		17)
			echo "$i"
			echo "bad luck from italy"
			;;
		*)
			echo "$i"
			;;
	esac
	((i++))
done
