#!/usr/bin/env bash
# Runs the whoami command under the user passed as argument.
if [ -z "$1" ]
then
    echo "Please provide a user name."
    exit 1
fi

# Run whoami as the specified user
sudo -u $1 whoami

